site_name: NIMH Data Science & Sharing Team

theme: material

plugins:
  - search

docs_dir: docs

nav:
  - About: index.md
  - Curations:
    - 06-M-0102 - Autism Subtypes Study:
      - (DRAFT) BIDS dataset_description.json: curations/06-M-0102/dataset_description.md
      - (DRAFT) BIDS README.md: curations/06-M-0102/README.md
    - 17-M-0181 - Healthy Volunteers Protocol:
      - Curation Notes: curations/17-M-0181/curation.md
    - OpenNeuro NIH C11 Leucine Studies:
      - (DRAFT) README.md: curations/c11-leucine/README.md
  - Guides:
      - NDA Tools Usage: tools/nda-downloadcmd.md
