site_name: NIMH Data Science & Sharing Team

theme: material

plugins:
  - search

docs_dir: docs

nav:
  - About: index.md
  - Curations:
    - 06-M-0102 - Autism Subtypes Study:
      - BIDS CHANGES: curations/06-M-0102/CHANGES.md
      - BIDS dataset_description.json: curations/06-M-0102/dataset_description.md
      - BIDS participants.json: curations/06-M-0102/participants.md
      - BIDS README: curations/06-M-0102/README.md
      - BIDS scans.json: curations/06-M-0102/scans.md
    - 17-M-0181 - Healthy Volunteers Protocol:
      - BIDS README.md: curations/17-M-0181/README.md
      - BIDS dataset_description.json: curations/17-M-0181/dataset_description.md
      - Curation Notes: curations/17-M-0181/curation.md
    - OpenNeuro NIH C11 Leucine Studies:
      - (DRAFT) README.md: curations/c11-leucine/README.md
  - Guides:
    - DataLad New User FAQ: guides/datalad/faq.md
    - NDA Tools Usage: guides/nda/downloadcmd.md
