site_name: NIMH Data Science & Sharing Team

theme: material

plugins:
  - search

docs_dir: docs

nav:
  - About: index.md
  - Curations:
    - 17-M-0181 - Healthy Volunteers Protocol: curations/17-M-0181.md
    - OpenNeuro NIH C11 Leucine Studies: curations/ds004291.md
